### PR TITLE
Election profile page: Fix "Individual contributions" section for future candidates

### LINKED ISSUE #2544: Election profile pages missing 2020 data for "Individual Contributions" section
Election profile pages are missing 2020 data for "Individual Contributions" section. This should be using full election data. 

- [ ] Passing `election_full=true` should solve this issue.

https://www.fec.gov/data/elections/president/2020/#individual-contributions
screen shot 2018-11-27 at 4 58 47 pm

### PR DESCRIPTION
**Pull request by lbeaufort**
## Summary (required)

- Resolves #2544: Fix "Individual contributions" section for future candidates
- Pass `election_full=true` for comparison table & map
## Impacted areas of the application
List general components of the application that this PR will affect:

-  Election profile pages of future presidential and senate candidates

### Before
image
screen shot 2018-11-27 at 6 08 17 pm

### After
screen shot 2018-11-27 at 6 06 49 pm
screen shot 2018-11-27 at 6 08 47 pm

## Related PRs
https://github.com/fecgov/fec-cms/pull/2254: Add future elections to election search & profile pages (This related PR missed the "Individual contributions" section)

## How to test
Include any information that may be helpful to the reviewer(s).
- http://localhost:8000/data/elections/senate/CA/2022/#individual-contributions
- http://localhost:8000/data/elections/president/2020/#individual-contributions

### CODE REVIEW

File: fec/fec/static/js/modules/tables.js [hunk 1]
```diff
@@ -882,7 +882,8 @@ function buildUrl(selected, context, path) {
   var query = {
     cycle: context.election.cycle,
     candidate_id: _.pluck(selected, 'candidate_id'),
-    per_page: 0
+    per_page: 0,
+    election_full: true
```
Comment (patphongs) [inline fec/fec/static/js/modules/tables.js]: This change looks like it's only effecting the `drawSizeTable` and `drawStateTable` functions, which is ok since we're trying to just fix schedule_a. But it makes it confusing that there's a separate `buildURL` function within this file, seems unnecessary and confusing. It might be better to delete this separate buildURL function altogether and define `var url = helpers.buildUrl()` directly within the `drawSizeTable` and `drawStateTable` functions. This is the same way that the maps.js does it. Seems clearer that way and more customizable.

For example, below would be for the drawSizeTable function. And you would make the same for the drawStateTable function, but modify the query to be by_state.

```
  var query = {
    cycle: context.election.cycle,
    candidate_id: _.pluck(selected, 'candidate_id'),
    per_page: 0,
    election_full: true
  };

  var url = helpers.buildUrl([
    'schedules',
    'schedule_a',
    'by_size',
    'by_candidate'
  ], query);

  $.getJSON(url).done(function(response) {
```

Comment (lbeaufort) [reply fec/fec/static/js/modules/tables.js]: @patphongs I made the changes, tested, and pointed this PR to the release branch. Can you take another look please?
